//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ActionMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ActionMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ActionMessages", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry ! Some records exist related to this record.Cannot Delete this record in their presence..
        /// </summary>
        internal static string Delete_Error_Exists_Message {
            get {
                return ResourceManager.GetString("Delete_Error_Exists_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry ! An error occurred while Deleting.Please review and Try again..
        /// </summary>
        internal static string Delete_Error_Message {
            get {
                return ResourceManager.GetString("Delete_Error_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Failed.
        /// </summary>
        internal static string Delete_Error_Title {
            get {
                return ResourceManager.GetString("Delete_Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected record is deleted Successfully..
        /// </summary>
        internal static string Delete_Successfull_Message {
            get {
                return ResourceManager.GetString("Delete_Successfull_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted Successfully.
        /// </summary>
        internal static string Delete_Title {
            get {
                return ResourceManager.GetString("Delete_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry ! An error occurred while loading data for editing.Please Try again.
        /// </summary>
        internal static string Edit_Error_Message {
            get {
                return ResourceManager.GetString("Edit_Error_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to Edit.
        /// </summary>
        internal static string Edit_Error_Title {
            get {
                return ResourceManager.GetString("Edit_Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Loaded Successfully for Editing.
        /// </summary>
        internal static string Edit_Successfull_Message {
            get {
                return ResourceManager.GetString("Edit_Successfull_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected Data Casting Exception Occurred.
        /// </summary>
        internal static string Exception_NullReference {
            get {
                return ResourceManager.GetString("Exception_NullReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected SQL Exception Occurred.
        /// </summary>
        internal static string Exception_SQL {
            get {
                return ResourceManager.GetString("Exception_SQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Unexpected Error occurred while Processing your Request. Please try Again. If you continue receiving this error, Contact Tech Support.
        /// </summary>
        internal static string GeneralError_Message {
            get {
                return ResourceManager.GetString("GeneralError_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected Error.
        /// </summary>
        internal static string GeneralError_Title {
            get {
                return ResourceManager.GetString("GeneralError_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data fetch failed. Please try again. If problem persists contact tech support..
        /// </summary>
        internal static string Load_Error_Message {
            get {
                return ResourceManager.GetString("Load_Error_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load .
        /// </summary>
        internal static string Load_Error_Title {
            get {
                return ResourceManager.GetString("Load_Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Loaded Successfully.
        /// </summary>
        internal static string Load_Success_Message {
            get {
                return ResourceManager.GetString("Load_Success_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Success.
        /// </summary>
        internal static string Load_Success_Title {
            get {
                return ResourceManager.GetString("Load_Success_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get data. Please try again. If problem persists contact tech support..
        /// </summary>
        internal static string NotFound_Message {
            get {
                return ResourceManager.GetString("NotFound_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Not Found.
        /// </summary>
        internal static string NotFound_Title {
            get {
                return ResourceManager.GetString("NotFound_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Record is Saved Successfully.Please enter the details.
        /// </summary>
        internal static string SaveMaster_Successfull_Message {
            get {
                return ResourceManager.GetString("SaveMaster_Successfull_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data received at server end, Please review and Try again ! If this problem persists contact support..
        /// </summary>
        internal static string Save_Error_DataNotReceived {
            get {
                return ResourceManager.GetString("Save_Error_DataNotReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry ! A record with same details exists. Please review and try again..
        /// </summary>
        internal static string Save_Error_Exists_Message {
            get {
                return ResourceManager.GetString("Save_Error_Exists_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry ! An error occurred while Saving.Please review and Try again.
        /// </summary>
        internal static string Save_Error_Message {
            get {
                return ResourceManager.GetString("Save_Error_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save failed.
        /// </summary>
        internal static string Save_Error_Title {
            get {
                return ResourceManager.GetString("Save_Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Record is Saved Successfully..
        /// </summary>
        internal static string Save_Successfull_Message {
            get {
                return ResourceManager.GetString("Save_Successfull_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Success.
        /// </summary>
        internal static string Save_Title {
            get {
                return ResourceManager.GetString("Save_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry ! An error occurred while Updating.Please review and Try again.
        /// </summary>
        internal static string Update_Error_Message {
            get {
                return ResourceManager.GetString("Update_Error_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Failed.
        /// </summary>
        internal static string Update_Error_Title {
            get {
                return ResourceManager.GetString("Update_Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected record is updated Successfully..
        /// </summary>
        internal static string Update_Successfull_Message {
            get {
                return ResourceManager.GetString("Update_Successfull_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Success.
        /// </summary>
        internal static string Update_Title {
            get {
                return ResourceManager.GetString("Update_Title", resourceCulture);
            }
        }
    }
}
